<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tenon.Repository\Tenon.Repository.csproj" />
    <ProjectReference Include="..\..\src\Tenon.Repository.MultiTenant\Tenon.Repository.MultiTenant.csproj" />
    <ProjectReference Include="..\..\src\Tenon.Repository.EfCore\Tenon.Repository.EfCore.csproj" />
    <ProjectReference Include="..\..\src\Tenon.Repository.EfCore.MultiTenant\Tenon.Repository.EfCore.MultiTenant.csproj" />
  </ItemGroup>

</Project>
